"""add phone column to checks

Revision ID: 102e88e984ce
Revises: 4e39e40f52a7
Create Date: 2025-07-31 13:55:53.491501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102e88e984ce'
down_revision: Union[str, Sequence[str], None] = '4e39e40f52a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'checks',
        sa.Column('phone', sa.String(), nullable=True),
    )
    # 2) заполняем старые строки
    op.execute(
        "UPDATE checks SET phone = '' WHERE phone IS NULL"
    )
    # 3) меняем на NOT NULL
    op.alter_column(
        'checks',
        'phone',
        existing_type=sa.String(),
        nullable=False,
    )


