"""fix withdrawstatus enum mapping

Revision ID: 88a779c5e7c5
Revises: 9bbaa6e5cd43
Create Date: 2025-08-01 15:49:56.477392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a779c5e7c5'
down_revision: Union[str, Sequence[str], None] = '9bbaa6e5cd43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
