"""Alter user_prices.user_id to BIGINT

Revision ID: 9612468fb354
Revises: e6d4003702f9
Create Date: 2025-07-31 15:31:47.503134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9612468fb354'
down_revision: Union[str, Sequence[str], None] = 'e6d4003702f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # меняем тип колонки user_id на BIGINT
    op.alter_column(
        'user_prices',
        'user_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        postgresql_using='user_id::bigint'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('user_prices', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
