"""add Price and UserPrice tables

Revision ID: e6d4003702f9
Revises: 102e88e984ce
Create Date: 2025-07-31 15:05:37.880774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d4003702f9'
down_revision: Union[str, Sequence[str], None] = '102e88e984ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('region_code', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('default_rub', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('region_code')
    )
    op.create_table('user_prices',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.String(), nullable=False),
    sa.Column('price_rub', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_code'], ['prices.region_code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'region_code')
    )
    op.create_index(op.f('ix_checks_phone'), 'checks', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checks_phone'), table_name='checks')
    op.drop_table('user_prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
